SUMMARY = "Inker backend, a self-hosted BYOS server for TRMNL e-ink displays"
DESCRIPTION = "NestJS/Express API server, SQLite via Prisma. Runs under \
plain node (upstream's own Dockerfile shows nothing in the app itself \
needs Bun -- Bun API usage is confined to *.test.ts; see meta-trmnl's \
Inker research notes). node/npm's own bitbake fetchers are both \
disabled upstream (SkipRecipe, \"disabled due to security issues\" -- \
bitbake/lib/bb/fetch2/npm*.py), so the production+dev npm closures are \
vendored the same way Terminus/LaraPaper vendor gems/composer \
packages: plain https://registry.npmjs.org SRC_URI entries pinned by \
a sha256 this layer computed itself, generated by \
scripts/gen-inker-npm.py, laid out into node_modules by \
do_configure/do_install from the accompanying path map (npm's own \
fetchers being disabled means there is no `npm install` to do that \
for us). Prisma's native query/schema engine binaries are a second, \
separate vendoring problem -- fetched directly from Prisma's own \
engines CDN (binaries.prisma.sh, the same host `prisma generate` \
downloads from itself, just done via SRC_URI instead of at do_compile \
network access) for the linux-arm64-openssl-3.0.x target, matching \
oe-core's OpenSSL 3.5.7 (the \"3.0.x\" ABI bucket) and this project's \
glibc target -- no x86_64 target exists unmodified upstream (see \
research notes), so arm64 is the only architecture this recipe \
supports, which keeps Inker's AGPL-3.0 SRCREV-pin compliance story \
simple per meta-trmnl/README.md. KNOWN INCOMPLETE this session: \
Puppeteer/Chromium screenshot rendering is out of scope (no \
meta-browser layer, consistent with LaraPaper's own Puppeteer gap) -- \
puppeteer's package files install but nothing downloads or runs a \
browser, so that one feature path will fail at runtime; everything \
else the backend needs to boot and serve its API is wired up."
HOMEPAGE = "https://github.com/usetrmnl/inker"
LICENSE = "AGPL-3.0-only"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/AGPL-3.0-only;md5=73f1eb20517c55bf9493b7dd6e480788"

# query-engine.so.node (library engineType, the prisma-client-js
# default) for linux-arm64-openssl-3.0.x + the schema-engine binary
# `db push` needs at runtime -- same commit hash
# node_modules/@prisma/engines-version's package.json records for the
# exact prisma/@prisma-client version this closure resolved to.
PRISMA_ENGINES_HASH = "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
PRISMA_ENGINES_TARGET = "linux-arm64-openssl-3.0.x"

SRC_URI = "git://github.com/usetrmnl/inker.git;protocol=https;branch=main;subpath=backend \
           file://0001-remove-dead-bullmq-files-left-over-from-an-abandoned-migration.patch \
           file://inker-backend.service \
           file://inker-backend.env \
           file://inker-backend-npm-map.json \
           https://binaries.prisma.sh/all_commits/${PRISMA_ENGINES_HASH}/${PRISMA_ENGINES_TARGET}/libquery_engine.so.node.gz;downloadfilename=prisma-libquery_engine.so.node.gz;unpack=0;name=prismaquerylib \
           https://binaries.prisma.sh/all_commits/${PRISMA_ENGINES_HASH}/${PRISMA_ENGINES_TARGET}/schema-engine.gz;downloadfilename=prisma-schema-engine.gz;unpack=0;name=prismaschema \
           "
SRCREV = "83c72b0c590cca40df9da1c646c3d5693e0028df"
PV = "0.6.0"

# git fetcher's subpath=backend unpacks straight to
# UNPACKDIR/backend (basename of subpath), not the usual
# UNPACKDIR/${BP} -- current bitbake always unpacks under UNPACKDIR,
# not WORKDIR (see ruby-terminus-gems's own S/UNPACKDIR fix).
S = "${UNPACKDIR}/backend"

SRC_URI[prismaquerylib.sha256sum] = "f46c5c49fad7402fd3cec5bc7cd827e5872895729430aa0715b84a548b2a77ae"
SRC_URI[prismaschema.sha256sum] = "2f1b52de49aa6d63a6fae488be18a05ee14305c024d7de52bc19b2285bcafd26"

include inker-backend-npm-prod.inc
include inker-backend-npm-dev.inc

DEPENDS = "nodejs-native"

inherit systemd useradd

INKER_APP_DIR = "${libdir}/inker-backend/app"

USERADD_PACKAGES = "${PN}"
USERADD_PARAM:${PN} = "--system --home-dir /var/lib/inker --shell /bin/false inker"

SYSTEMD_PACKAGES = "${PN}"
SYSTEMD_SERVICE:${PN} = "inker-backend.service"
SYSTEMD_AUTO_ENABLE:${PN} = "enable"

python do_configure() {
    import json
    import os
    import tarfile

    unpackdir = d.getVar("UNPACKDIR")
    s = d.getVar("S")

    with open(os.path.join(unpackdir, "inker-backend-npm-map.json")) as f:
        pkgmap = json.load(f)

    for path, info in pkgmap.items():
        dest = os.path.join(s, path)
        bb.utils.mkdirhier(dest)
        with tarfile.open(os.path.join(unpackdir, info["file"])) as tf:
            members = []
            for m in tf.getmembers():
                parts = m.name.split("/", 1)
                if len(parts) == 2 and parts[1]:
                    m.name = parts[1]
                    members.append(m)
            tf.extractall(dest, members=members)
        # Some npm packages ship files/dirs with odd owner permission
        # bits in their published tarball (pngjs's lib/ and coverage/
        # ship as mode 0o622, no execute/search bit at all) --
        # harmless for a real `npm install` (npm normalizes
        # permissions), but tarfile preserves them verbatim, and a
        # later plain `rm -rf` (do_rm_work, or bitbake's own do_unpack
        # re-run) can't even traverse into them, let alone unlink.
        # OR in full owner rwx unconditionally -- never removes an
        # existing permission, just guarantees traversal/removal works.
        for root, dirs, files in os.walk(dest):
            for name in dirs + files:
                p = os.path.join(root, name)
                if os.path.islink(p):
                    continue
                os.chmod(p, os.stat(p).st_mode | 0o700)
}

do_compile() {
    install -d ${S}/prisma-engines
    gunzip -c ${UNPACKDIR}/prisma-libquery_engine.so.node.gz > ${S}/prisma-engines/libquery_engine.so.node
    gunzip -c ${UNPACKDIR}/prisma-schema-engine.gz > ${S}/prisma-engines/schema-engine
    chmod +x ${S}/prisma-engines/schema-engine

    cd ${S}

    # prisma generate FIRST -- it populates node_modules/@prisma/client
    # and node_modules/.prisma/client with the schema-specific model
    # types (Device, Screen, Setting, ...). tsc below imports
    # PrismaService which extends that generated PrismaClient; running
    # tsc before generate compiles against the unconfigured stub
    # @prisma/client ships on npm, which has no model accessors at all
    # -- every `this.prisma.<model>` access fails type-checking
    # (TS2339 x247, one per call site, all the same root cause).
    export HOME="${S}"
    export PRISMA_QUERY_ENGINE_LIBRARY="${S}/prisma-engines/libquery_engine.so.node"
    export PRISMA_SCHEMA_ENGINE_BINARY="${S}/prisma-engines/schema-engine"
    export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
    node node_modules/prisma/build/index.js generate --schema=prisma/schema.prisma

    # generate embeds its own absolute S path as debug-only provenance
    # strings (config.generator.output/sourceFilePath) -- never read at
    # runtime (engine loading goes through the PRISMA_*_LIBRARY/BINARY
    # env vars above), but do_package_qa's buildpaths check rightly
    # rejects TMPDIR leaking into a shipped file.
    sed -i "s|${S}|.|g" node_modules/.prisma/client/index.js \
        node_modules/.prisma/client/edge.js node_modules/.prisma/client/wasm.js

    # Plain tsc, not `nest build` -- nest-cli.json turns that into a
    # webpack build, which would need webpack/webpack-node-externals as
    # extra devDependencies for no real benefit here. --outDir/--rootDir
    # override tsconfig.json's own outDir so dist/main.js lands flat
    # (tsconfig has no rootDir, so plain `tsc -p` would nest output
    # under dist/src/ instead). Sourcemaps/declarations off: no need to
    # ship them, and tsc bakes absolute build paths into sourcemaps,
    # which do_package's buildpaths QA would otherwise catch.
    node node_modules/typescript/lib/tsc.js -p tsconfig.json \
        --outDir dist --rootDir src \
        --sourceMap false --declaration false --declarationMap false

    # prisma/seed.ts is outside tsconfig.json's "include" -- compile it
    # on its own so it ships as plain JS runnable under node instead of
    # relying on Bun's direct-.ts-execution.
    node node_modules/typescript/lib/tsc.js prisma/seed.ts --outDir prisma \
        --module commonjs --target ES2021 --esModuleInterop --skipLibCheck \
        --resolveJsonModule --sourceMap false
}

python do_install() {
    import json
    import os
    import shutil

    s = d.getVar("S")
    unpackdir = d.getVar("UNPACKDIR")
    app = d.getVar("D") + d.getVar("INKER_APP_DIR")

    bb.utils.mkdirhier(app)
    shutil.copytree(os.path.join(s, "dist"), os.path.join(app, "dist"))
    bb.utils.mkdirhier(os.path.join(app, "prisma"))
    shutil.copy(os.path.join(s, "prisma", "schema.prisma"), os.path.join(app, "prisma", "schema.prisma"))
    shutil.copy(os.path.join(s, "prisma", "seed.js"), os.path.join(app, "prisma", "seed.js"))
    shutil.copy(os.path.join(s, "package.json"), os.path.join(app, "package.json"))
    shutil.copytree(os.path.join(s, "prisma-engines"), os.path.join(app, "prisma-engines"))
    # Static screen assets (default-screen.png, setup.png, e-ink fonts)
    # -- SetupScreenService/DefaultScreenService/SleepScreenService all
    # join(process.cwd(), "assets") and were never getting it; without
    # setup.png already present, SetupScreenService.onModuleInit() (runs
    # during NestJS bootstrap, before app.listen()) falls through to
    # regenerating it, which needs a writable assets/ this package never
    # shipped either.
    shutil.copytree(os.path.join(s, "assets"), os.path.join(app, "assets"))

    # Production-only node_modules -- the same map.json do_configure
    # used, filtered by its own "dev" flag (packages needed only to
    # compile: typescript, @types/*, eslint, ... never ship).
    with open(os.path.join(unpackdir, "inker-backend-npm-map.json")) as f:
        pkgmap = json.load(f)
    for path, info in pkgmap.items():
        if info.get("dev"):
            continue
        dest = os.path.join(app, path)
        bb.utils.mkdirhier(os.path.dirname(dest))
        # dirs_exist_ok: some map entries nest under another entry's own
        # destination (e.g. @nestjs/serve-static's private path-to-regexp
        # copy) -- do_configure's tarfile.extractall already merges those
        # in S without complaint, so do_install's copy needs to as well.
        shutil.copytree(os.path.join(s, path), dest, symlinks=True, dirs_exist_ok=True)

    # `prisma generate`'s own output: node_modules/@prisma/client (a
    # fetched prod package, already copied above) gets populated in
    # place, but node_modules/.prisma/client is new generated content,
    # not a fetched package -- not in the map, copy it separately.
    prisma_generated = os.path.join(s, "node_modules", ".prisma")
    if os.path.isdir(prisma_generated):
        shutil.copytree(prisma_generated, os.path.join(app, "node_modules", ".prisma"))

    # node-gyp-build/prebuildify packages (bare-fs, bare-path, bare-url)
    # ship one prebuilt native addon per platform in their own npm
    # tarball; only linux-arm64 ever loads here, and the darwin/win32/
    # android/x86 siblings are non-ELF or wrong-arch ELF that do_package's
    # objcopy debug-split can't parse and dies on. Drop everything but
    # the one this target actually uses.
    for root, dirs, _files in os.walk(app):
        if os.path.basename(root) == "prebuilds":
            for pdir in list(dirs):
                if pdir != "linux-arm64":
                    shutil.rmtree(os.path.join(root, pdir))
                    dirs.remove(pdir)

    # screen-designer.controller.ts fs.mkdirSync()s './uploads/widgets'
    # (and captures/drawings) at module-load time, relative to cwd --
    # SCREENS_DIR/FIRMWARE_DIR are configurable env vars but these three
    # are not. Upstream's own docker-compose.yml volume-mounts a real
    # writable directory at exactly this same app-relative path
    # (`uploads_data:/app/uploads`); the ExecStartPre mkdir -p in
    # inker-backend.service already pre-creates all five subdirs under
    # /var/lib/inker/uploads -- symlink is the missing piece connecting
    # the app's own relative path to that writable StateDirectory.
    os.symlink("/var/lib/inker/uploads", os.path.join(app, "uploads"))

    # Same story for src/config/logger.config.ts's winston File
    # transports (`logs/error.log`, `logs/combined.log`, NODE_ENV ===
    # "production" only, which this deployment always is) -- relative
    # to cwd, and ExecStartPre already mkdir -p's /var/lib/inker/logs.
    os.symlink("/var/lib/inker/logs", os.path.join(app, "logs"))

    # do_configure's tarball-extraction fixup (`| 0o700`) only ever
    # granted the OWNER (root/pseudo, at build time) rwx -- it never
    # touched group/other bits, so an npm package that ships a file
    # with no group/other read bit (e.g. proxy-from-env inside
    # proxy-agent, published 0600) is unreadable by inker-backend's
    # own runtime user and crashes with EACCES. Ensure a sane minimum
    # everywhere the app tree actually ships.
    for root, dirs, files in os.walk(app):
        for name in dirs:
            p = os.path.join(root, name)
            if not os.path.islink(p):
                os.chmod(p, os.stat(p).st_mode | 0o755)
        for name in files:
            p = os.path.join(root, name)
            if not os.path.islink(p):
                os.chmod(p, os.stat(p).st_mode | 0o644)

    etc = d.getVar("D") + d.getVar("sysconfdir") + "/inker"
    bb.utils.mkdirhier(etc)
    shutil.copy(os.path.join(unpackdir, "inker-backend.env"), os.path.join(etc, "inker-backend.env"))

    unitdir = d.getVar("D") + d.getVar("systemd_system_unitdir")
    bb.utils.mkdirhier(unitdir)
    shutil.copy(os.path.join(unpackdir, "inker-backend.service"), os.path.join(unitdir, "inker-backend.service"))
}

FILES:${PN} = "${INKER_APP_DIR} ${sysconfdir}/inker ${systemd_system_unitdir}"

RDEPENDS:${PN} = "nodejs libssl libcrypto"

# Vendored prebuilt binaries (Prisma's engines, sharp's @img/sharp-*
# .node addons) ship stripped with no separate debuginfo by design --
# same reasoning as larapaper-vendor.inc.
INSANE_SKIP:${PN} += "already-stripped"
