#!/usr/bin/env python3
"""Regenerate recipes-trmnl/larapaper/larapaper-vendor.inc from a
usetrmnl/larapaper checkout's composer.lock.

Usage: gen-larapaper-vendor.py /path/to/larapaper/checkout

composer.lock's "packages" array (as opposed to "packages-dev") is already
the fully resolved production dependency closure -- unlike Gemfile.lock,
no separate transitive-closure computation is needed. Each package's
"dist" zip is downloaded once here to compute its sha256 (composer.lock's
own "shasum" field is routinely empty; composer verifies via the "reference"
field instead, so this script pins its own checksum the same way
gen-terminus-gems.py pins rubygems checksums).
"""
import hashlib
import json
import pathlib
import sys
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
OUT_DIR = HERE.parent / "recipes-trmnl" / "larapaper"


def safe_name(pkg_name):
    return pkg_name.replace("/", "-").replace(".", "_")


def main():
    checkout = pathlib.Path(sys.argv[1])
    lock = json.loads((checkout / "composer.lock").read_text())
    packages = lock["packages"]

    entries = []
    for pkg in packages:
        name = pkg["name"]
        version = pkg["version"]
        dist = pkg["dist"]
        assert dist["type"] == "zip", f"{name}: unexpected dist type {dist['type']}"
        url = dist["url"]
        sname = safe_name(name)
        # Flat filename (no subdir) so do_compile can glob
        # ${UNPACKDIR}/composer-vendor-*.zip, matching the pattern
        # ruby-terminus-gems.bb uses for ${UNPACKDIR}/*.gem.
        dlname = f"composer-vendor-{sname}-{version}.zip"

        print(f"fetching {name} {version}...", file=sys.stderr)
        with urllib.request.urlopen(url) as resp:
            data = resp.read()
        sha256 = hashlib.sha256(data).hexdigest()

        entries.append((name, version, url, sname, dlname, sha256))

    out = OUT_DIR / "larapaper-vendor.inc"
    with out.open("w") as f:
        f.write("# Auto-generated by scripts/gen-larapaper-vendor.py -- do not hand-edit.\n")
        f.write(f"# Production composer dependency closure: {len(entries)} packages,\n")
        f.write("# from composer.lock's own \"packages\" array (packages-dev excluded,\n")
        f.write("# matches --no-dev at install time). See larapaper-vendor.bb.\n\n")
        f.write('SRC_URI += "\\\n')
        for name, version, url, sname, dlname, sha256 in entries:
            f.write(f"    {url};name={sname};downloadfilename={dlname};unpack=0 \\\n")
        f.write('    "\n\n')
        for name, version, url, sname, dlname, sha256 in entries:
            f.write(f'SRC_URI[{sname}.sha256sum] = "{sha256}"\n')

    print(f"wrote {out} ({len(entries)} packages)", file=sys.stderr)


if __name__ == "__main__":
    main()
