#!/usr/bin/env python3
"""Regenerate recipes-trmnl/terminus/terminus-gems-{pure,native}.inc from a
usetrmnl/terminus checkout's Gemfile + Gemfile.lock.

Usage: gen-terminus-gems.py /path/to/terminus/checkout

Resolves the production gem closure (Gemfile's top-level, non-grouped gems
plus their transitive deps from Gemfile.lock) and splits it into pure-Ruby
gems vs. native-extension gems, using Gemfile.lock's CHECKSUMS section
(sha256, present since a recent Bundler lockfile format) as the SRC_URI
checksum -- no custom bitbake fetcher needed, plain https + sha256sum works.

Native-extension gems are further split at generation time into "ships
with Ruby already" (skipped, assumed satisfied by Ruby's own bundled
default gems -- see RUBY_BUNDLED_NATIVE below) vs. "genuinely new, needs
cross-compilation" (written to terminus-gems-native.inc). That file is a
machine-readable WORKLIST only -- nothing includes it. Native-extension
gems get hand-written recipes/rubygems-*.bb recipes instead, since they
need meta-rubygems' cross-compiling rubygems.bbclass, not a host-side
`gem install`.
"""
import re
import sys
import json
import tarfile
import gzip
import io
import hashlib
import urllib.request
import pathlib

# Only these three actually match ruby 4.0.6's bundled/default versions
# (racc 1.8.1, io-console 0.8.2, stringio 3.2.0) -- confirmed by extracting
# the real ruby-4.0.6.tar.gz. bigdecimal/erb/json/prism/rbs/strscan were
# wrongly skipped on this same assumption. This is a hardcoded snapshot for
# ruby 4.0.6, not a real version check -- re-verify against the ruby
# recipe's version before the next Terminus SRCREV bump.
RUBY_BUNDLED_NATIVE = {"io-console", "racc", "stringio"}

HERE = pathlib.Path(__file__).resolve().parent
OUT_DIR = HERE.parent / "recipes-trmnl" / "terminus"


PLATFORM_SUFFIX_RE = re.compile(
    r"-(x86_64|aarch64|arm64|arm)-(linux-gnu|linux-musl|darwin|mingw32)$"
)


def parse_lock(lock_text):
    """Returns (specs, platform_only) -- specs[name] is the plain/"ruby"
    platform spec if one exists; platform_only is the set of gem names
    for which Gemfile.lock carries ONLY precompiled per-platform specs
    (no source gem at all, e.g. nokogiri) -- those can never be safely
    vendored generically, they need a real source build."""
    m = re.search(r"^GEM\n.*?^  specs:\n(.*?)\n\n", lock_text, re.S | re.M)
    specs = {}
    platform_names = set()
    cur = None
    cur_is_platform = False
    for line in m.group(1).split("\n"):
        if re.match(r"^    \S", line):
            mm = re.match(r"^    (\S+) \(([^)]+)\)", line)
            cur, version = mm.group(1), mm.group(2)
            cur_is_platform = bool(PLATFORM_SUFFIX_RE.search(version))
            if cur_is_platform:
                platform_names.add(cur)
            else:
                specs[cur] = {"version": version, "deps": []}
        elif re.match(r"^      \S", line) and not cur_is_platform:
            mm = re.match(r"^      (\S+)", line)
            specs[cur]["deps"].append(mm.group(1))

    platform_only = platform_names - specs.keys()

    checks = {}
    mc = re.search(r"^CHECKSUMS\n(.*?)\n\n", lock_text, re.S | re.M)
    for line in mc.group(1).split("\n"):
        mm = re.match(r"^  (\S+) \(([^)]+)\) sha256=([0-9a-f]+)", line)
        if mm:
            checks[(mm.group(1), mm.group(2))] = mm.group(3)
    return specs, checks, platform_only


def parse_prod_gems(gemfile_text):
    prod, depth = [], 0
    for line in gemfile_text.split("\n"):
        if re.match(r"^group ", line):
            depth += 1
            continue
        if line.strip() == "end" and depth > 0:
            depth -= 1
            continue
        if depth == 0:
            mm = re.match(r'^gem "([^"]+)"', line)
            if mm:
                prod.append(mm.group(1))
    return prod


def closure(prod, specs):
    seen = set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        for d in specs.get(name, {}).get("deps", []):
            visit(d)

    for g in prod:
        visit(g)
    return seen


def fetch_gem(name, version):
    url = f"https://rubygems.org/gems/{name}-{version}.gem"
    with urllib.request.urlopen(url) as resp:
        return resp.read()


def has_native_ext(name, version):
    """Download the .gem, inspect metadata.gz for a non-empty extensions: list."""
    data = fetch_gem(name, version)
    tf = tarfile.open(fileobj=io.BytesIO(data))
    meta = gzip.decompress(tf.extractfile("metadata.gz").read()).decode()
    m = re.search(r"^extensions:\n((?:- .+\n)+)", meta, re.M)
    return bool(m)


def emit(gems, path, label):
    with open(path, "w") as f:
        f.write("# Auto-generated by scripts/gen-terminus-gems.py -- do not hand-edit.\n")
        f.write(f"# {label}: {len(gems)} gems.\n\n")
        f.write('SRC_URI += "\\\n')
        for g in gems:
            f.write(f'    https://rubygems.org/gems/{g["name"]}-{g["version"]}.gem;name={g["name"]};unpack=0 \\\n')
        f.write('    "\n\n')
        for g in gems:
            f.write(f'SRC_URI[{g["name"]}.sha256sum] = "{g["sha256"]}"\n')


def main():
    checkout = pathlib.Path(sys.argv[1])
    lock_text = (checkout / "Gemfile.lock").read_text()
    gemfile_text = (checkout / "Gemfile").read_text()

    specs, checks, platform_only = parse_lock(lock_text)
    prod = parse_prod_gems(gemfile_text)
    names = sorted(closure(prod, specs) - {"bundler"})

    pure, native, skipped = [], [], []
    for name in names:
        if name in platform_only:
            # Gemfile.lock carries only precompiled per-platform gems for
            # this name (e.g. nokogiri) -- no plain "ruby" platform spec,
            # and thus no checksum we can trust for a generic target. Use
            # the LOCKED version (platform suffix stripped), not whatever
            # is latest on rubygems.org today -- a previous version of this
            # script fetched "latest" here, which silently drifted from
            # what Gemfile.lock actually pins. This always needs a real
            # cross-compile, never vendor it as pure.
            locked_version = next(
                v for (n, v) in checks if n == name
            )
            version = PLATFORM_SUFFIX_RE.sub("", locked_version)
            sha = hashlib.sha256(fetch_gem(name, version)).hexdigest()
            native.append({"name": name, "version": version, "sha256": sha})
            continue
        spec = specs.get(name)
        if spec is None:
            continue
        version = spec["version"]
        sha = checks.get((name, version))
        entry = {"name": name, "version": version, "sha256": sha}
        if name in RUBY_BUNDLED_NATIVE:
            skipped.append(entry)
            continue
        if has_native_ext(name, version):
            native.append(entry)
        else:
            pure.append(entry)

    emit(pure, OUT_DIR / "terminus-gems-pure.inc", "pure-ruby production gems")
    emit(native, OUT_DIR / "terminus-gems-native.inc",
         "native-extension production gems (cross-compile status: see recipe)")

    print(f"pure: {len(pure)}", file=sys.stderr)
    print(f"native (new, needs cross-compile): {len(native)} {[g['name'] for g in native]}", file=sys.stderr)
    print(f"  of which platform-only in Gemfile.lock: {sorted(platform_only)}", file=sys.stderr)
    print(f"skipped (assumed ruby-bundled): {len(skipped)} {[g['name'] for g in skipped]}", file=sys.stderr)


if __name__ == "__main__":
    main()
